Map context dispatches to functions
Imageus-OSS/client pull request #182
Opened 2021-05-29 02:47 UTC by suneettipirneni

Uses predefined functions instead of raw objects for dispatching actions:

Before:
```js
dispatch({
 type: 'updateUser',
 payload: userInfo
});
```

After:
```js
dispatch(UserActions.updateUser(userInfo));
```

Hopefully this helps with calling the functions and prevents wrong inputs being passed in.

2021-05-29 17:28 UTC, ctcuff requested changes
Code looks good but there are a few small bugs:

- Creating a group causes the page to crash with an error: `TypeError: Cannot read property 'publicGroup' of undefined`
- Deleting an image doesn't update the UI (although the image is removed when you refresh)

2021-05-29 20:33 UTC, suneettipirneni commented
> Code looks good but there are a few small bugs:
> 
> * Creating a group causes the page to crash with an error: `TypeError: Cannot read property 'publicGroup' of undefined`
> * Deleting an image doesn't update the UI (although the image is removed when you refresh)

The first bug has been fixed, but it turns out the second bug is actually present in the main branch I've created an issue to track that: #184

2021-05-30 04:03 UTC, ctcuff requested changes
Ok one last little bug I swear: if you create a group using a user that initially isn't a member of any group, the page crashes with the error: `TypeError: Cannot read property 'inviteCode' of undefined`

2021-05-30 04:31 UTC, suneettipirneni commented
> Ok one last little bug I swear: if you create a group using a user that initially isn't a member of any group, the page crashes with the error: `TypeError: Cannot read property 'inviteCode' of undefined`

I'll look into it, also don't feel bad about bringing up bugs, it's part of the review process! 😄

2021-05-31 18:58 UTC, ctcuff approved these changes
LGTM

2021-05-31 19:18 UTC, merged